import {
  Folder,
  File,
  FileText,
  Image,
  Code,
  Settings,
  FolderGit,
  Package,
  Book,
  LucideIcon,
  Terminal,
  AudioLines,
  Video,
  Database,
  Archive,
  Banknote,
  Server,
  Network,
  Key,
  AlertCircle,
  FolderTree,
  FileCode,
  FileJson,
  LayoutGrid,
  Music,
  Film,
  HardDrive,
  Shield,
  Lock
} from "lucide-react";

// Map icon names to Lucide React components
const iconMap: Record<string, LucideIcon> = {
  folder: Folder,
  file: File,
  "file-text": FileText,
  image: Image,
  code: Code,
  settings: Settings,
  "folder-git": FolderGit,
  package: Package,
  book: Book,
  terminal: Terminal,
  "audio-lines": AudioLines,
  video: Video,
  database: Database,
  archive: Archive,
  banknote: Banknote,
  server: Server,
  network: Network,
  key: Key,
  "alert-circle": AlertCircle,
  "folder-tree": FolderTree,
  "file-code": FileCode,
  "file-json": FileJson,
  "layout-grid": LayoutGrid,
  music: Music,
  film: Film,
  "hard-drive": HardDrive,
  shield: Shield,
  lock: Lock,
};

export function getIconComponent(iconName: string): LucideIcon {
  return iconMap[iconName] || File;
}